// The bundled ECharts basemap uses several abbreviated or historical names.
// Keep those presentation-specific aliases separate from AQUASTAT and UN names.
export const mapNameToIso3: Record<string, string> = {
  'Antigua and Barb.': 'ATG',
  'Bolivia': 'BOL',
  'Bosnia and Herz.': 'BIH',
  'Brunei': 'BRN',
  'Cape Verde': 'CPV',
  'Central African Rep.': 'CAF',
  'Czech Rep.': 'CZE',
  'Dem. Rep. Congo': 'COD',
  'Dem. Rep. Korea': 'PRK',
  'Dominican Rep.': 'DOM',
  'Eq. Guinea': 'GNQ',
  'Iran': 'IRN',
  'Korea': 'KOR',
  'Lao PDR': 'LAO',
  'Macedonia': 'MKD',
  'Micronesia': 'FSM',
  'Moldova': 'MDA',
  'Netherlands': 'NLD',
  'Russia': 'RUS',
  'S. Sudan': 'SSD',
  'São Tomé and Principe': 'STP',
  'Solomon Is.': 'SLB',
  'St. Vin. and Gren.': 'VCT',
  'Swaziland': 'SWZ',
  'Syria': 'SYR',
  'Tanzania': 'TZA',
  'Turkey': 'TUR',
  'United Kingdom': 'GBR',
  'United States': 'USA',
  'Venezuela': 'VEN',
  'Vietnam': 'VNM',
}
